modLoader = "javafml"
loaderVersion = "4,"

license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"

authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "viatora.png"
credits = "${mod_credits}"

[[mixins]]
config = "viatora.mixins.json"

[[dependencies.viatora]]
modId = "neoforge"
type = "required"
versionRange = "21,"
ordering = "NONE"
side = "BOTH"

[[dependencies.viatora]]
modId = "minecraft"
type = "required"
versionRange = "1.21.1,1.22"
ordering = "NONE"
side = "BOTH"